### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by pietroppeter** [zetashift/nimibujo#1]
to replace the default stylesheet with this new one, one way is to do like in [numericalnim](https://pietroppeter.github.io/nimib/numerical.html) and after `nbInit` add a line of code:
```nim
nbDoc.context["stylesheet"] = """<link rel="stylesheet" href="style.css">"""
```

(path will need to be handled either by doing as in nimibook or waiting for some improvements in nimib that will improve path handling)

If then you have other changes you will apply you can make a template for this theme and have an api like this
```nim
import nimib, nimibujo

nbInit
nbUseNimibujo
```

**Comment by zetashift** [comment]
Thanks!:+1: I was making this in a very spartan way haha. 

_PS: Your NumericalNim link links to this issue btw._

**Comment by pietroppeter** [comment]
Fixed the link, it was actually empty...

**Comment by zetashift** [comment]
I fixed this in the PR, I'm closely following the path handling RFC!
